// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Text.RegexProvider")>]
[<assembly: AssemblyProductAttribute("FSharp.Text.RegexProvider")>]
[<assembly: AssemblyDescriptionAttribute("A type provider for regular expressions.")>]
[<assembly: AssemblyVersionAttribute("2.0.2")>]
[<assembly: AssemblyFileVersionAttribute("2.0.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Text.RegexProvider"
    let [<Literal>] AssemblyProduct = "FSharp.Text.RegexProvider"
    let [<Literal>] AssemblyDescription = "A type provider for regular expressions."
    let [<Literal>] AssemblyVersion = "2.0.2"
    let [<Literal>] AssemblyFileVersion = "2.0.2"
